#!/bin/bash

# Quick DNS Setup Script for rpc.flora.network
# This creates a simple round-robin DNS configuration

echo "================================"
echo "Flora RPC DNS Setup"
echo "================================"
echo ""
echo "Add these DNS records to your domain provider:"
echo ""
echo "Option 1: Round-Robin (Simple, Free)"
echo "-------------------------------------"
echo "Type: A    Name: rpc    Value: 52.9.17.25     TTL: 60"
echo "Type: A    Name: rpc    Value: 50.18.34.12    TTL: 60"
echo "Type: A    Name: rpc    Value: 204.236.162.240 TTL: 60"
echo ""
echo "Option 2: Using existing seed domains"
echo "--------------------------------------"
echo "Type: CNAME    Name: rpc    Value: seed1.testnet.flora.network    TTL: 300"
echo ""
echo "After adding DNS records, test with:"
echo "--------------------------------------"
echo "# Wait 5 minutes for DNS propagation, then:"
echo "nslookup rpc.flora.network"
echo ""
echo "curl -X POST -H 'Content-Type: application/json' \\"
echo "  --data '{\"jsonrpc\":\"2.0\",\"method\":\"eth_chainId\",\"params\":[],\"id\":1}' \\"
echo "  http://rpc.flora.network:8545"
echo ""
echo "================================"
echo "For HTTPS/Load Balancing:"
echo "================================"
echo "See terraform/ directory for AWS ALB setup"
echo "This will provide:"
echo "- HTTPS support"
echo "- Health checks"
echo "- Automatic failover"
echo "- Professional endpoint"
echo ""